# Prefix: Ctrl+A
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -sg escape-time 10

# true color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# split with | and -, keep current path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "reloaded"

# ---- Rosé Pine Moon ----
set -g status-style 'bg=#2a273f fg=#e0def4'
set -g status-left  '#[fg=#232136,bg=#c4a7e7,bold]  #S #[fg=#c4a7e7,bg=#2a273f]'
set -g status-right '#[fg=#908caa] %a %d %b #[fg=#e0def4,bold]%H:%M '
set -g status-left-length 30
setw -g window-status-format         '#[fg=#908caa]  #I #W  '
setw -g window-status-current-format '#[fg=#f6c177,bold]  #I #W  '
set -g pane-border-style        'fg=#393552'
set -g pane-active-border-style 'fg=#c4a7e7'
set -g message-style            'bg=#393552 fg=#e0def4'
set -g mode-style               'bg=#393552 fg=#e0def4'
